### ISSUE TITLE
mcmcphase is not opening

### ISSUE THREAD

**Issue by u11114537** [james-monkeyshines/rna-phase-3#1]
Dear Simon,

I hope this email finds you well.

I tried to open mcmcphase or mlphase but when I click on the executable it tries to open but closes straight away. Do you know what could be the problem? I also tried to opened via cdm but it is not working although I get on the screen 
"usage : mcmcphase.exe control_file"

Be safe in this current covid situation.
Kind Regards,
Rosa

**Comment by james-monkeyshines** [comment]
Hello Rosa,
The program needs to be run from a command line, and requires a control file to execute - that's what the admittedly terse usage message is trying to tell you. Please see the [user guide](https://github.com/james-monkeyshines/rna-phase-3/blob/master/PHASE-3.0.pdf) for details on creating a control file (and instructions for the programs in general).

Cheers,
James
